package com.example.ielts;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class TaskSelectionScreen {

    private Scene scene;
    private Stage primaryStage;

    public TaskSelectionScreen(Stage primaryStage) {
        this.primaryStage = primaryStage;
        createScene();
    }

    private void createScene() {

        VBox root = new VBox(40);
        root.setAlignment(Pos.TOP_CENTER);
        root.setPadding(new Insets(60));
        root.getStyleClass().add("root");

        /* ---------- Title ---------- */
        Label title = new Label("IELTS Writing Practice");
        title.getStyleClass().add("title");

        Label subtitle = new Label(
                "Sharpen your writing skills with AI-powered feedback based on official IELTS band descriptors"
        );
        subtitle.getStyleClass().add("subtitle");
        subtitle.setWrapText(true);
        subtitle.setMaxWidth(700);

        /* ---------- Cards ---------- */
        HBox cardContainer = new HBox(30);
        cardContainer.setAlignment(Pos.CENTER);

        VBox task1Card = createTaskCard(
                "Task 1",
                "Describe visual information: processes, graphs, charts, diagrams, or maps",
                "20 minutes",
                "150+ words",
                () -> startTask(1)
        );

        VBox task2Card = createTaskCard(
                "Task 2",
                "Write an essay responding to a point of view, argument, or problem",
                "40 minutes",
                "250+ words",
                () -> startTask(2)
        );

        cardContainer.getChildren().addAll(task1Card, task2Card);

        /* ---------- Footer ---------- */
        Label footer = new Label(
                "Questions are generated by AI to simulate real IELTS exam conditions. " +
                        "Your response will be evaluated against official band descriptors."
        );
        footer.getStyleClass().add("subtitle");
        footer.setWrapText(true);
        footer.setMaxWidth(700);

        root.getChildren().addAll(title, subtitle, cardContainer, footer);

        scene = new Scene(root, 1100, 750);
        scene.getStylesheets().add(
                getClass().getResource("/com/example/ielts/theme.css").toExternalForm()
        );
    }

    /* ===================================================== */

    private VBox createTaskCard(
            String taskTitle,
            String description,
            String time,
            String words,
            Runnable action
    ) {
        VBox card = new VBox(15);
        card.setPadding(new Insets(30));
        card.setPrefWidth(420);
        card.setAlignment(Pos.TOP_LEFT);
        card.getStyleClass().add("card");

        Label title = new Label(taskTitle);
        title.getStyleClass().add("section-title");

        Label desc = new Label(description);
        desc.getStyleClass().add("subtitle");
        desc.setWrapText(true);

        Label meta = new Label("⏱ " + time + "    ✍ " + words);
        meta.getStyleClass().add("subtitle");

        Button startBtn = new Button("Start " + taskTitle);
        startBtn.getStyleClass().add("button-primary");
        startBtn.setPrefHeight(44);
        startBtn.setMaxWidth(Double.MAX_VALUE);
        startBtn.setOnAction(e -> action.run());

        card.getChildren().addAll(title, desc, meta, startBtn);
        return card;
    }

    /* ===================================================== */

    private void startTask(int taskNumber) {
        WritingTaskScreen taskScreen = new WritingTaskScreen(primaryStage, taskNumber);
        primaryStage.setScene(taskScreen.getScene());
    }

    public Scene getScene() {
        return scene;
    }
}
