package com.example.ielts;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class TaskSelectionScreen {

    private Scene scene;
    private Stage primaryStage;

    public TaskSelectionScreen(Stage primaryStage) {
        this.primaryStage = primaryStage;
        createScene();
    }

    private void createScene() {

        VBox root = new VBox(40);
        root.setAlignment(Pos.TOP_CENTER);
        root.setPadding(new Insets(60));
        root.setStyle("-fx-background-color: #f8f9fb;");

        /* ---------- Title ---------- */
        Label title = new Label("IELTS Writing Practice");
        title.setStyle(
                "-fx-font-family: 'Times New Roman';" +
                        "-fx-font-size: 42px;" +
                        "-fx-font-weight: bold;" +
                        "-fx-text-fill: #1f2937;"
        );

        Label subtitle = new Label(
                "Sharpen your writing skills with AI-powered feedback based on official IELTS band descriptors"
        );
        subtitle.setWrapText(true);
        subtitle.setMaxWidth(700);
        subtitle.setAlignment(Pos.CENTER);
        subtitle.setStyle(
                "-fx-font-family: 'Times New Roman';" +
                        "-fx-font-size: 16px;" +
                        "-fx-text-fill: #6b7280;"
        );

        /* ---------- Cards ---------- */
        HBox cardContainer = new HBox(30);
        cardContainer.setAlignment(Pos.CENTER);

        VBox task1Card = createTaskCard(
                "Task 1",
                "Describe visual information: processes, graphs, charts, diagrams, or maps",
                "20 minutes",
                "150+ words",
                () -> startTask(1)
        );

        VBox task2Card = createTaskCard(
                "Task 2",
                "Write an essay responding to a point of view, argument, or problem",
                "40 minutes",
                "250+ words",
                () -> startTask(2)
        );

        cardContainer.getChildren().addAll(task1Card, task2Card);

        /* ---------- Footer ---------- */
        Label footer = new Label(
                "Questions are generated by AI to simulate real IELTS exam conditions. " +
                        "Your response will be evaluated against official band descriptors."
        );
        footer.setWrapText(true);
        footer.setMaxWidth(700);
        footer.setAlignment(Pos.CENTER);
        footer.setStyle(
                "-fx-font-family: 'Times New Roman';" +
                        "-fx-font-size: 13px;" +
                        "-fx-text-fill: #6b7280;"
        );

        root.getChildren().addAll(title, subtitle, cardContainer, footer);
        scene = new Scene(root, 1100, 750);
    }

    /* ===================================================== */

    private VBox createTaskCard(
            String taskTitle,
            String description,
            String time,
            String words,
            Runnable action
    ) {
        VBox card = new VBox(15);
        card.setPadding(new Insets(30));
        card.setPrefWidth(420);
        card.setAlignment(Pos.TOP_LEFT);

        String normalStyle =
                "-fx-background-color: white;" +
                        "-fx-border-color: #e5e7eb;" +
                        "-fx-border-width: 2;" +
                        "-fx-border-radius: 16;" +
                        "-fx-background-radius: 16;";

        String hoverStyle =
                "-fx-background-color: white;" +
                        "-fx-border-color: #facc15;" +
                        "-fx-border-width: 2;" +
                        "-fx-border-radius: 16;" +
                        "-fx-background-radius: 16;";

        card.setStyle(normalStyle);

        Label title = new Label(taskTitle);
        title.setStyle(
                "-fx-font-family: 'Times New Roman';" +
                        "-fx-font-size: 22px;" +
                        "-fx-font-weight: bold;" +
                        "-fx-text-fill: #111827;"
        );

        Label desc = new Label(description);
        desc.setWrapText(true);
        desc.setStyle(
                "-fx-font-family: 'Times New Roman';" +
                        "-fx-font-size: 14px;" +
                        "-fx-text-fill: #6b7280;"
        );

        Label meta = new Label("⏱ " + time + "    ✍ " + words);
        meta.setStyle(
                "-fx-font-family: 'Times New Roman';" +
                        "-fx-font-size: 13px;" +
                        "-fx-text-fill: #6b7280;"
        );

        Button startBtn = new Button("Start " + taskTitle);
        startBtn.setPrefHeight(44);
        startBtn.setMaxWidth(Double.MAX_VALUE);
        startBtn.setStyle(
                "-fx-font-family: 'Times New Roman';" +
                        "-fx-background-color: #1f2a44;" +
                        "-fx-text-fill: white;" +
                        "-fx-font-size: 14px;" +
                        "-fx-background-radius: 10;" +
                        "-fx-cursor: hand;"
        );

        /* ---------- Hover Effect ---------- */
        startBtn.setOnMouseEntered(e -> card.setStyle(hoverStyle));
        startBtn.setOnMouseExited(e -> card.setStyle(normalStyle));

        startBtn.setOnAction(e -> action.run());

        card.getChildren().addAll(title, desc, meta, startBtn);
        return card;
    }

    /* ===================================================== */

    private void startTask(int taskNumber) {
        WritingTaskScreen taskScreen = new WritingTaskScreen(primaryStage, taskNumber);
        primaryStage.setScene(taskScreen.getScene());
    }

    public Scene getScene() {
        return scene;
    }
}
